### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by nickbytes** [nickbytes/nickbytes.github.io#1]
- [ ] Real content
- [ ] Get Basscss through npm
- [ ] Set up Gulp tasks
  - [ ] CSS
  - [ ] JS
  - [ ] PSI
  - [ ] Deploy?
- [ ] Techniques for max page speed
  - [ ] Inline CSS?
